Repository ltechkorea/inference_results_v1.0, pull requests merged in 2021-07, with the labels that each got.

#10 feat(nuild): define #9 `DATASET_DIR` and `MLPERF_SCRATCH_PATH`
  closed/NVIDIA/Makefile
Labels: enhancement, pre-submit

#11 system list update
  closed/NVIDIA/code/common/system_list.py
  closed/NVIDIA/configs/resnet50/Server/config.json
Labels: image classification, medical imaging, natural language processing, object detection, recommendation, speech to text

#18 Update `config.json` for All Topologies
  closed/LTechKorea/Makefile
  closed/LTechKorea/code/__init__.py
  closed/LTechKorea/code/common/__init__.py
  closed/LTechKorea/code/harness/CMakeLists.txt
  closed/LTechKorea/code/harness/cscope.files
  closed/LTechKorea/code/harness/harness_rnnt/metadata.hpp
  closed/LTechKorea/code/harness/harness_rnnt/warmup.hpp
  closed/LTechKorea/code/main.py
  closed/LTechKorea/configs/bert/Server/config.json
  closed/LTechKorea/configs/dlrm/Offline/config.json
  closed/LTechKorea/configs/dlrm/Server/config.json
  closed/LTechKorea/configs/resnet50/Offline/config.json
  closed/LTechKorea/configs/resnet50/Server/config.json
  closed/LTechKorea/configs/rnnt/Offline/config.json
  closed/LTechKorea/configs/rnnt/Server/config.json
  closed/LTechKorea/configs/ssd-resnet34/Offline/config.json
  closed/LTechKorea/configs/ssd-resnet34/Server/config.json
  closed/LTechKorea/run_arg.txt
Labels: image classification, medical imaging, natural language processing, object detection, pre-submit, recommendation, speech to text
